CUDNN_BENCHMARK: false
DATA:
  BATCH_SIZE: 64
  CLASS_WEIGHTS_TYPE: "none"
  CROPSIZE: 224
  DATAPATH: "/nlsasfs/home/neol/rushar/vpt_workspace/vpt/data_dw"
  FEATURE: "sup_vitb16_imagenet21k"
  MULTILABEL: false
  NAME: "vtab-dmlab"
  NO_TEST: false
  NUMBER_CLASSES: 171
  NUM_WORKERS: 1
  PERCENTAGE: 1.0
  PIN_MEMORY: true

DBG: false
DIST_BACKEND: "nccl"
DIST_INIT_FILE: ""
DIST_INIT_PATH: "env://"

MODEL:
  ADAPTER:
    REDUCATION_FACTOR: 8
    STYLE: "Pfeiffer"
  LINEAR:
    MLP_SIZES: []
    DROPOUT: 0.1
  MLP_NUM: 0
  MODEL_ROOT: "/nlsasfs/home/neol/rushar/vpt_workspace/vpt/models_dw"
  PROMPT:
    CLSEMB_FOLDER: ""
    CLSEMB_PATH: ""
    DEEP: true
    DEEP_SHARED: false
    DROPOUT: 0.1
    FORWARD_DEEP_NOEXPAND: false
    INITIATION: "random"
    LOCATION: "prepend"
    NUM_DEEP_LAYERS: null
    NUM_TOKENS: 100
    PROJECT: -1
    REVERSE_DEEP: false
    SAVE_FOR_EACH_EPOCH: false
    VIT_POOL_TYPE: "original"
  SAVE_CKPT: false
  TRANSFER_TYPE: "prompt"
  TYPE: "vit"
  WEIGHT_PATH: ""

NUM_GPUS: 0
NUM_SHARDS: 1
OUTPUT_DIR: "/nlsasfs/home/neol/rushar/vpt_workspace/vpt/out_dir/vtab-dmlab/sup_vitb16_imagenet21k/lr0.25_wd0.001/run1"
RUN_N_TIMES: 5
SEED: 42

SOLVER:
  BASE_LR: 0.25
  BIAS_MULTIPLIER: 1.0
  DBG_TRAINABLE: false
  LOG_EVERY_N: 100
  LOSS: "softmax"
  LOSS_ALPHA: 0.01
  MOMENTUM: 0.9
  OPTIMIZER: "sgd"
  PATIENCE: 300
  SCHEDULER: "cosine"
  TOTAL_EPOCH: 100
  WARMUP_EPOCH: 10
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_BIAS: 0
